### ISSUE TITLE
Fahrplan: Icon für Train oder Bus ändern

### ISSUE THREAD

**Issue by australien340** [tt-tom17/MyScripts#3]
Hallo Tom

die Icons für die Ausgabe des Train oder Bus sind sich sehr ähnlich, kann man diese ändern?

Danke

**Comment by tt-tom17** [comment]
Hi,
ja da lässt sich was machen, werde mal ein Mapping erstellen. Das der Fahrzeugtyp vom Fahrplan ein Icon aus der Icon Datei zugewiesen werden kann. Kann aber etwas dauern, wegen der Feiertage.

**Comment by australien340** [comment]
Super! Danke für den schnellen  Support.

Schöne Feiertage wüsche ich!
